In [144]:
import pandas as pd
import numpy as np
import sklearn.linear_model as lm
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as mse
import glob
import os
from sklearn.metrics import mean_squared_error
from math import sqrt

In [82]:
path = r'C:\Desktop\учеба\дипло\thecode\measurments'

In [99]:
filenames = ['Temirlan_summary.txt', 'Lera_summary.txt', 'Lev_summary.txt', 'Angelina_summary.txt', 'Deniska_summary.txt', 'Yarik_summary.txt', 'Sofa_summary.txt']

In [100]:
df = []
for filename in filenames:
    li = pd.read_csv(filename, index_col = None, header=None, sep='\t')
    df.append(li)

    

In [101]:
df = pd.concat(df, axis = 0, ignore_index=True)

In [102]:
df.rename(columns={0: 'shift', 1: 'bpm', 2: 'attitude', 3: 'bp'}, inplace=True)

In [103]:
df

shift  bpm  attitude   bp
0   0.785   93     0.381  130
1   0.829   79     0.404  130
2   0.678   75     0.378  130
3   0.786   79     0.390  130
4   0.791   84     0.418  130
5   0.862   84     0.415  130
6   0.836   75     0.420  130
7   0.802   79     0.423  130
8   0.824   79     0.425  130
9   0.844   84     0.417  130
10  0.569   79     0.350  110
11  0.607   75     0.369  110
12  0.693   71     0.363  110
13  0.685   75     0.371  110
14  0.613   79     0.354  110
15  0.598   84     0.361  110
16  0.580   79     0.351  110
17  0.602   84     0.366  110
18  0.651   79     0.367  110
19  0.655   84     0.369  110
20  0.972   71     0.336  120
21  0.984   79     0.317  120
22  0.973   71     0.333  120
23  0.976   75     0.342  120
24  0.971   66     0.345  120
25  0.977   93     0.364  120
26  0.985  106     0.355  120
27  0.984   97     0.348  120
28  0.995   75     0.316  120
29  1.010   66     0.297  120
..    ...  ...       ...  ...
40  1.013   48     0.332  120
41  1.035   84     0.309  120
42  1.005   66     0.335  120
43  1.010   57     0.317  120
44  1.009   62     0.318  120
45  1.036   79     0.333  120
46  1.026   57     0.321  120
47  1.024   71     0.347  120
48  1.033   71     0.312  120
49  1.030   62     0.308  120
50  0.966   66     0.386  100
51  0.974   62     0.373  100
52  0.973   66     0.412  100
53  0.959   66     0.387  100
54  0.946   62     0.392  100
55  0.956  110     0.399  100
56  0.927   93     0.388  100
57  0.984   57     0.384  100
58  0.978   62     0.377  100
59  0.961   57     0.389  100
60  0.720  115     0.391  110
61  0.684   97     0.400  110
62  0.743   88     0.312  110
63  0.765  123     0.283  110
64  0.768  101     0.316  110
65  0.773   84     0.355  110
66  0.787   62     0.325  110
67  0.724   84     0.332  110
68  0.792   71     0.319  110
69  0.745   79     0.400  110

[70 rows x 4 columns]

In [125]:
df = df.sample(n=70, random_state=42)

In [127]:
df

shift  bpm  attitude   bp
22  0.973   71     0.333  120
0   0.785   93     0.381  130
49  1.030   62     0.308  120
4   0.791   84     0.418  130
54  0.946   62     0.392  100
18  0.651   79     0.367  110
10  0.569   79     0.350  110
33  0.598  123     0.402  100
45  1.036   79     0.333  120
12  0.693   71     0.363  110
31  0.700   71     0.329  100
9   0.844   84     0.417  130
67  0.724   84     0.332  110
5   0.862   84     0.415  130
62  0.743   88     0.312  110
30  0.725   57     0.311  100
58  0.978   62     0.377  100
35  0.696  123     0.428  100
57  0.984   57     0.384  100
47  1.024   71     0.347  120
16  0.580   79     0.351  110
34  0.655   79     0.317  100
42  1.005   66     0.335  120
28  0.995   75     0.316  120
7   0.802   79     0.423  130
53  0.959   66     0.387  100
40  1.013   48     0.332  120
44  1.009   62     0.318  120
46  1.026   57     0.321  120
19  0.655   84     0.369  110
..    ...  ...       ...  ...
6   0.836   75     0.420  130
36  0.679   62     0.323  100
64  0.768  101     0.316  110
69  0.745   79     0.400  110
68  0.792   71     0.319  110
15  0.598   84     0.361  110
27  0.984   97     0.348  120
41  1.035   84     0.309  120
26  0.985  106     0.355  120
48  1.033   71     0.312  120
24  0.971   66     0.345  120
59  0.961   57     0.389  100
63  0.765  123     0.283  110
11  0.607   75     0.369  110
32  0.636   79     0.328  100
66  0.787   62     0.325  110
61  0.684   97     0.400  110
37  0.660  119     0.375  100
29  1.010   66     0.297  120
43  1.010   57     0.317  120
65  0.773   84     0.355  110
1   0.829   79     0.404  130
52  0.973   66     0.412  100
21  0.984   79     0.317  120
2   0.678   75     0.378  130
23  0.976   75     0.342  120
20  0.972   71     0.336  120
60  0.720  115     0.391  110
14  0.613   79     0.354  110
51  0.974   62     0.373  100

[70 rows x 4 columns]

In [128]:
df[['shift', 'bpm', 'attitude']][:5].values

array([[ 0.973, 71.   ,  0.333],
       [ 0.785, 93.   ,  0.381],
       [ 1.03 , 62.   ,  0.308],
       [ 0.791, 84.   ,  0.418],
       [ 0.946, 62.   ,  0.392]])

In [129]:
X_train, X_test, y_train, y_test = df[['shift', 'bpm', 'attitude']][:50].values, df[['shift', 'bpm', 'attitude']][50:].values,df['bp'][:50].values,df['bp'][50:].values



In [130]:
skm = lm.LinearRegression()
skm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [131]:
skm.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

In [137]:
result = skm.predict(X_test)

In [139]:
np.mean(result/y_test)

1.0080214503477536

In [140]:
result

array([115.40468885, 117.77237883, 107.09428521, 108.02102072,
       106.25542643, 109.61539026, 112.03273874, 110.1236847 ,
       113.41578282, 114.55554794, 111.32929018, 115.66525966,
       119.56787729, 114.13243016, 110.31854737, 115.43166365,
       114.92569166, 112.54145336, 107.28667055, 117.15846875])

In [141]:
y_test

array([120, 100, 110, 110, 100, 110, 110, 100, 120, 120, 110, 130, 100,
       120, 130, 120, 120, 110, 110, 100], dtype=int64)

In [143]:
np.mean(abs(result - y_test))

7.545716971444852

In [134]:
predicted = skm.predict(X_test)

In [135]:
mse(predicted, y_test)

96.75106053718613

In [145]:
rms = sqrt(mean_squared_error(y_test, predicted))

In [146]:
rms

9.836211696440156